version: 0.0
os: linux

files:
  - source: html/
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      runas: root
  Install:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root
